# -*- coding: utf-8 -*-
"""granite-3.2-2b-instruct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//huggingface.co/ibm-granite/granite-3.2-2b-instruct.ipynb
"""

!pip install -U transformers

"""## Local Inference on GPU
Model page: https://huggingface.co/ibm-granite/granite-3.2-2b-instruct

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/ibm-granite/granite-3.2-2b-instruct)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

!pip install transformers accelerate gradio sentencepiece

import re
import gradio as gr
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# ---------------------- CONFIGURATION ----------------------
#HF_TOKEN = "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"   # <<--- PUT YOUR TOKEN HERE
MODEL_NAME = "ibm-granite/granite-3.2-2b-instruct"
# -----------------------------------------------------------

# Load model
pipe = pipeline(
    "text-generation",
    model=MODEL_NAME,
    tokenizer=MODEL_NAME,
    token=HF_TOKEN,
    device_map="auto",
    max_new_tokens=512,
    temperature=0.1
)

# Clause splitting pattern
def split_into_clauses(text):
    return re.split(r";|\n|\.", text)

# LLM Call Helper
def ask_llm(prompt):
    return pipe([{"role": "user", "content": prompt}])[0]["generated_text"]

# Main processing function
def clause_analyzer(document):
    clauses = [c.strip() for c in split_into_clauses(document) if c.strip()]

    results = []
    for i, clause in enumerate(clauses, start=1):

        # Simplification
        simple_prompt = f"Simplify the following legal clause in plain English:\n\n{clause}"
        simplified = ask_llm(simple_prompt)

        # Entity extraction
        ner_prompt = f"""
Extract key information from the clause. Return in JSON strictly with fields:
party_names, dates, obligations, monetary_values, penalties, duration, jurisdiction.
Clause: {clauses}
"""
        entities = ask_llm(ner_prompt)

        results.append(
            f"🔹 **Clause {i}:**\n{clause}\n\n"
            f"➡ **Simplified:**\n{simplified}\n\n"
            f"📌 **Extracted Entities:**\n{entities}\n\n---"
        )

    return "\n".join(results)

# ---------- Gradio UI ----------
input_doc = gr.Textbox(label="Paste Legal Document", lines=15)
output_res = gr.Markdown(label="Clause-wise Analysis Result")

gr.Interface(
    fn=clause_analyzer,
    inputs=input_doc,
    outputs=output_res,
    title="⚖️ Clause-Wise Legal Document Analyzer",
    description="AI-powered analyzer using IBM Granite 3.2 2B Instruct\nSplits → Simplifies → Extracts key legal entities.",
    allow_flagging="never"
).launch()

